#https://docs.docker.com/compose/compose-file/build/
#https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker/6211677-creez-un-fichier-docker-compose-pour-orchestrer-vos-conteneurs

version: '3' 

services:

#-------------- MARIADB -------------#
#https://www.youtube.com/watch?v=Zk1CUU2ivqc
#https://mariadb.com/kb/en/setting-up-a-lamp-stack-with-docker-compose/
    mariadb:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: "mariadb"
        restart: always
        volumes:
            - mariadb_data:/var/lib/mysql
        expose:
            - "3306"
        env_file:
            - .env
        networks:
            - inception
        tty: true

#--------------- NGINX --------------#
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: "nginx"
        depends_on:
            - wordpress
        restart: always
        env_file:
            - .env
        ports:
            - "443:443"
        volumes:
            - worpress_data:/var/www/html/wordpress
        networks:
            - inception
        tty: true

#------------- WORDPRESS ------------#
#https://www.youtube.com/watch?v=yWNUu7zHW6g&list=PLn6POgpklwWqaC1pdx02SrrgOaL2ZL7G0&index=11
    wordpress:
        image: debian:buster
        restart: on-failure
        env_file:
            - .env
        volumes:
            - data:/var/www/html
        expose: 
            - "9000"
        networks:
            - inception
        tty: true

networks:
    inception:
        driver: bridge

volumes:
        mariadb_data:
            driver: local
            driver_opts:
                o: bind
                type: none
                device: /home/lcavallu/data/mysql
        wordpress_data:
            driver: local
            driver_opts:
                type: none
                device: /home/lcavallu/data/wordpress
                o: bind
